### ISSUE TITLE
[1.19.3 Quilt] Missing translations for clay balls

### ISSUE THREAD

**Issue by TelepathicGrunt** [remotegetaway/sakurarosea#1]
Just something tiny I noticed. There seems to be missing lang translations for the two clay balls. 
![image](https://user-images.githubusercontent.com/40846040/219535600-c83f963a-8c7d-4da3-aab8-5116d83f82d3.png)
![image](https://user-images.githubusercontent.com/40846040/219535616-7cf90c7e-08a3-4451-87ff-55811b5be45e.png)

**Comment by remotegetaway** [comment]
real, forgot to add '_ball' to names
